z09liner/core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

z09liner/forum/urls.py
from django.contrib import admin
from django.urls import path
from forum.views import category_list, topic_detail, topic_list, topic_filter_new, \
    topic_filter_author, topic_filter_takepart, complain


app_name = 'forum'

urlpatterns = [
    path('', category_list, name='category_list'),
    path('topic_list/<int:detail_pk>/', topic_list, name='topic_list'),
    path('topic/<int:topic_pk>/', topic_detail, name='topic_detail'),
    path('topic_filter_new/', topic_filter_new, name='topic_filter_new'),
    path('topic_filter_author/', topic_filter_author, name='topic_filter_author'),
    path('topic_filter_takepart/', topic_filter_takepart, name='topic_filter_takepart'),
    path('<int:post_pk>/complain/', complain, name='complain'),
]

z09liner/system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

z09liner/users/urls.py
from django.urls import path
from users.views import login, register, profile, logout

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

z09liner/forum/models.py
from django.db import models
from users.models import User


class Category(models.Model):
    title = models.CharField(
        max_length=48, blank=True, null=True
    )

    def __str__(self):
        return f'{self.title}'


class CategoryDetail(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True
                                 , related_name='children'
                                 )
    detail_title = models.CharField(max_length=100, blank=True)
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f'{self.detail_title}'


class Topic(models.Model):
    category_detail = models.ForeignKey(
        CategoryDetail, on_delete=models.CASCADE, blank=True, null=True, related_name='topics'
    )
    title = models.CharField(
        max_length=100, verbose_name='Заголовок', blank=True, null=True
    )
    additional_info = models.TextField(blank=True)

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE, verbose_name='Тема', related_name='posts'
    )
    text = models.TextField(
        verbose_name='текст'
    )
    created = models.DateTimeField(
        verbose_name='дата создания',
        auto_now_add=True
    )
    published = models.DateTimeField(
        verbose_name='дата публикации'
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        blank=True, null=True
    )

    def __str__(self):
        return f'{self.text}'

z09liner/forum/forms.py
from django import forms
from forum.models import Topic, Post
from django.forms import ModelForm, Textarea


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
        )
        widgets = {
            'text': Textarea(attrs={'rows': 4, 'cols': 60}),
        }


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = (
            'title',
            # 'additional_info'
        )
        widgets = {
            'title': Textarea(attrs={'rows': 1}),
            # 'additional_info': Textarea(attrs={'rows': 4, 'cols': 80}),
        }


class EmailPostForm (forms.Form):
    name = forms.CharField(max_length=48)
    email = forms.EmailField()
    comments = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 5}))

z09liner/forum/views.py
from datetime import datetime
from datetime import timedelta

from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Count
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect

from forum.models import Category, CategoryDetail, Topic, Post
from forum.forms import PostForm, TopicForm, EmailPostForm


def category_list(request):
    categories = Category.objects.all()
    main_topics = Topic.objects.annotate(num_posts=Count('posts')).filter(num_posts__gte=1).order_by('-num_posts')[:6]
    return render(request, 'forum/category_list.html',
                  {
                      'categories': categories,
                      'main_topics': main_topics
                  })


def topic_list(request, detail_pk):
    parent_topic = CategoryDetail.objects.get(pk=detail_pk)
    topics = Topic.objects.filter(category_detail=detail_pk)
    counter_topics = topics.count()
    paginator = Paginator(topics, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    if request.method == 'POST':
        topic_form = TopicForm(request.POST)
        if topic_form.is_valid():
            topic = topic_form.save(commit=False)
            topic.author = request.user
            topic.category_detail = CategoryDetail.objects.filter(pk=detail_pk).first()
            topic.save()
            return redirect('forum:topic_list', detail_pk=parent_topic.pk)
    else:
        topic_form = TopicForm()
    return render(request, 'forum/topic_list.html', {'parent_topic': parent_topic,
                                                     'topics': topics,
                                                     'topic_form': topic_form,
                                                     'counter_topics': counter_topics,
                                                     'page': page
                                                     })


def topic_detail(request, topic_pk):
    topic = Topic.objects.get(pk=topic_pk)
    posts = Post.objects.filter(topic=topic_pk)
    counter = posts.count()
    paginator = Paginator(posts, 10)
    page_num = request.GET.get('page', 1)
    page = paginator.get_page(page_num)
    is_paginated = page.has_other_pages()
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.published = datetime.now()
            post.topic = Topic.objects.filter(pk=topic_pk).first()
            post.save()
            return redirect('forum:topic_detail', topic_pk=topic.pk)
    else:
        post_form = PostForm()
    context = {
                   'topic': topic,
                   'posts': posts,
                   'counter': counter,
                   'post_form': post_form,
                   'page': page,
                   'is_paginated': is_paginated,
                   }
    return render(request, 'forum/topic_detail.html', context)


def topic_filter_new(request):
    now = datetime.now()
    day_ago = now - timedelta(days=1)
    new_topics = Topic.objects.filter(posts__created__gte=day_ago)
    context = {
        'new_topics': new_topics
    }
    return render(request, 'forum/topic_filter_new.html', context)


def topic_filter_author(request):
    author_topics = Topic.objects.filter(author=request.user)
    context = {
        'author_topics': author_topics
    }
    return render(request, 'forum/topic_filter_author.html', context)


def topic_filter_takepart(request):
    take_part_topics = Topic.objects.filter(posts__author=request.user)
    context = {
        'take_part_topics': take_part_topics
    }
    return render(request, 'forum/topic_filter_takepart.html', context)


def complain(request, post_pk):
    post = Post.objects.filter(pk=post_pk).first()
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            subject = (form.cleaned_data['name'], form.cleaned_data['email'])
            post_text = post.text
            complain_text = (form.cleaned_data['comments'])
            massage = f'Сообщение форума {post_text} вызвало жалобу {complain_text}'
            mail = send_mail(subject, massage, 'usermail.2021@mail.ru', ['olga_muhina81@mail.ru'], fail_silently=True)
            if mail:
                messages.success(request, 'Письмо отправлено')
                return redirect('forum:complain', post_pk=post.pk)
            else:
                messages.error(request, 'Ошибка отправки')
    else:
        form = EmailPostForm()
    context = {
        'post': post,
        'form': form
               }
    return render(request, 'forum/complain.html', context)

z09liner/forum/templates/forum/category_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div style="margin-left: 15%; margin-right: 15%">
        <table width="100%"; cellpadding="10"; cellspacing="0" >
        <tr>
            <td width="100%" height="40" bgcolor="#f0f8ff" >
                <a href="{% url 'forum:topic_filter_new' %}">
                    Новое за 24 часа
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                {% if user.is_authenticated %}
                {% csrf_token %}
                <a href="{% url 'forum:topic_filter_author' %}">
                    Мои темы
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'forum:topic_filter_takepart' %}">
                    Темы, в которых я участвую
                </a>
                {% endif %}
            </td>
        </table>
</div>

<div
        style="font-size: 18px; margin-left: 15%; margin-right: 15%" xmlns:>
    <h2 style="margin: 20px">Форум</h2>

    <div>
        <table width="100%"; cellpadding="10"; cellspacing="0">
        <tr>
            <td width="80%" height="40" bgcolor="#add8e6"><b> Важное </b></td>
            <td width="20%" rowspan="99">
                <img src="https://cdn2.static1-sima-land.com/items/2714020/0/400.jpg" width="400" height="400" alt="карамелька">
            </td>
        </tr>
            <tr>
                <td width="80%">
                    <br>
                    {% for main_topic in main_topics %}
                    <a href="{% url 'forum:topic_detail' main_topic.pk %}" style="color: red"> !!! {{main_topic}} </a>
                    <h8 style="font-size: 0.75em"> {{main_topic.posts.count}} сообщений </h8></br><br>
                    {% endfor %}
                </td>
                <td width="20%"></td>
            </tr>
        </table>
    </div>

    <div>
        <table width="100%" bgcolor="#f0f8ff" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2">
        {% for category in categories %}
            <tr>
                <td width="80%" bgcolor="#add8e6"> <b>{{category.title}}</b></td>
                <td width="20%" bgcolor="#add8e6" style="font-size: 0.75em; text-align: right"> <b>Темы</b>
<!--                    </br> Сообщения -->
                </td>
            </tr>
            {% for category_detail in category.children.all %}
                <tr>
                    <td width="80%">
                        <a href="{% url 'forum:topic_list' category_detail.pk %}" style="color: #18397c">
                            {{category_detail}}
                        </a></br>
                        <p style="font-size: 0.75em">
                            {{category_detail.description}}
                        </p>
                         <hr style="margin: 0">
                    </td>
                    <td width="20%" style="font-size: 0.75em; text-align: right"> <b>{{category_detail.topics.count}}</b>
<!--                        </br> количество сообщений-->
<!--                        {% for topic in category_detail.topics.all %}-->
<!--&lt;!&ndash;                        нужна сумма&ndash;&gt;-->
<!--                        {{ topic.posts.count }}-->
<!--                        {% endfor %}-->

                    </td>
                </tr>
            {% endfor %}
        {% endfor %}

        </table>
    </div>
</div>

{% endblock content %}

z09liner/forum/templates/forum/complain.html
{% extends 'core/base.html' %}

{% load static %}
{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <b><li style="margin-right: 15%; margin-left: 15%; color: red" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li></b>
    {% endfor %}
</ul>
{% endif %}

<h2 style="margin-left: 15%">
    Пожаловаться
</h2>
<p style="margin-left: 15%; margin-right: 15%"> Текст сообщения форума:</br>
<p style="margin-right: 15%; margin-left: 15%"> {{post.text}} </p>

<form style="margin-left: 15%; margin-right: 15%" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary btn-block">
        Отправить
    </button>
</form>

{% endblock content %}

z09liner/forum/templates/forum/topic_detail.html
{% extends 'core/base.html' %}

{% load static %}
{% block content %}
<h2 style="margin-left: 15%; margin-right: 15%">
    {{topic.title}}</h2></br>
<!--    <div style="margin-left: 15%; margin-right: 15%; margin-bottom: 20px">-->
<!--        {{topic.additional_info}}-->
<!--    </div>-->

<a href="{% url 'forum:category_list' %}" style="margin-left: 15%"> Вернуться на главную форума </a>
<br>
<table bgcolor="#add8e6" ; cellpadding="10"; cellspacing="1"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="20%">
            {% if user.is_authenticated %}
            {% csrf_token %}
            <button class="btn btn-warning"><a href="#post">Ответить</a></button>
            {% else %}
            <button class="btn btn-warning"><a href="{% url 'users:login' %}">Ответить</a></button>
            {% endif %}
        </td>

        <td width="60%">
<nav aria-label="..." style="margin-left: 15%">
  <ul class="pagination">

      <li class="page-item">
          {% if page.has_previous %}
          <a class="page-link" href="{% url 'forum:topic_detail' topic_pk=topic.pk %}?page={{ page.previous_page_number }}" tabindex="-1">Предыдущая</a>
          {% endif %}
      </li>

      {% for n in page.paginator.page_range %}
      {% if page.number == n %}
          <li class="page-item active">
              <a class="page-link" href="{% url 'forum:topic_detail' topic_pk=topic.pk %}?page={{ n }}">{{n}}<span class="sr-only">(current)</span></a>
          </li>
      {% elif n > page.number|add:-3 and n < page.number|add:3 %}
          <li class="page-item">
              <a class="page-link" href="{% url 'forum:topic_detail' topic_pk=topic.pk %}?page={{ n }}">{{n}}</a>
          </li>
      {% endif %}
      {% endfor %}
      {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'forum:topic_detail' topic_pk=topic.pk %}?page={{ page.next_page_number }}">Следующая</a>
    </li>
      {% endif %}
  </ul>
</nav>
        </td>
        <td width="20%" style="text-align: right">
            Всего {{counter}} сообщений
        </td>
    </tr>
</table>
<table bgcolor="#f0f8ff" ; border="1"; bordercolor="white"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    {% for post in page.object_list %}
    <tr>
        <td width="20%">
            {{post.author}}</br>
            <img width="100" height="100"
                     src="{% if post.author.image %} {{ post.author.image.url }} {% else %} {% static 'img/users/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
        </td>
        <td width="60%"><a name="post"></a>
            <p style="color: #4e555b; font-size: 0.75em"> <b style="color: red">#</b> {{post.published}}</p></br>
            {{post.text|safe}}
             <hr style="margin: 0">
        </td>
        <td width="20%">
            <a href="{% url 'forum:complain' post.pk %}" style="margin-left: 15%; font-size: 0.75em" onclick=""> Пожаловаться </p></a>
        </td>
    </tr>
    {% empty %}
    <p style="margin-left: 15%">Здесь пока никто ничего не обсуждал - задайте свой вопрос</p>
    {% endfor %}
</table>

{% if user.is_authenticated %}
{% csrf_token %}


<table bgcolor="#fffacd" ; border="1"; bordercolor="white"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="20%">
            <h5>{{user.username}}</h5>
            </br>
           <img width="100" height="100"
                     src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/users/default_avatar.jpg' %} {% endif %}"
                     class="img-thumbnail">
        </td>
        <td width="60%">
            <p style="color: #4e555b; font-size: 0.75em"> # {{post.published}}</p></br>
            <form action="" method="POST">
                {% csrf_token %}
                {{ post_form.as_p }}
            <button type="submit" class="btn btn-warning">Добавить сообщение</button>
        </form>
        </td>
        <td width="20%"></td>
    </tr>
</table>
{% endif %}

{% endblock content %}

z09liner/forum/templates/forum/topic_filter_author.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<a href="{% url 'forum:category_list' %}" style="margin-left: 15%"> Вернуться на главную форума </a>
<h2 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px">Мои темы</h2>
<h4 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px; color: #1b6d85">
   (найдено {{author_topics.count}} тем(ы)) </br>
</h4>


<table bgcolor="#add8e6" ; border="1"; bordercolor="#d3d3d3"; cellpadding="5"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="100%" style="text-align: center">
<!--            paginator-->
        </td>
    </tr>
</table>
<table bgcolor="#f0f8ff" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">

    {% for author_topic in author_topics %}
    <tr>
        <td width="60%">
            <a href="{% url 'forum:topic_detail' author_topic.pk %}" style="color: #18397c">{{author_topic}}</a>
            <hr style="margin: 0">
        </td>
        <td width="20%" style="font-size: 0.75em"> </td>
        <td width="20%" style="font-size: 0.75em"; align="right"> {{author_topic.posts.count}} </td>
    </tr>
    {% empty %}
    <p style="margin-left: 15%">
        По вашему запросу ничего не найдено
    </p>
    {% endfor %}
</table>

{% endblock content %}

z09liner/forum/templates/forum/topic_filter_new.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<a href="{% url 'forum:category_list' %}" style="margin-left: 15%"> Вернуться на главную форума </a>
<h2 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px">Новое за 24 часа</h2>
<h4 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px; color: #1b6d85">
   (найдено {{new_topics.count}} тем(ы)) </br>
</h4>


<table bgcolor="#add8e6" ; border="1"; bordercolor="#d3d3d3"; cellpadding="5"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="100%" style="text-align: center">
<!--        paginator-->
        </td>
    </tr>
</table>
<table bgcolor="#f0f8ff" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">

    {% for new_topic in new_topics %}
    <tr>
        <td width="60%">
            <a href="{% url 'forum:topic_detail' new_topic.pk %}" style="color: #18397c">{{new_topic}}</a>
            <hr style="margin: 0">
        </td>
        <td width="20%" style="font-size: 0.75em"> </td>
        <td width="20%" style="font-size: 0.75em"; align="right"> {{new_topic.posts.count}} </td>
    </tr>
    {% empty %}
    <p style="margin-left: 15%">
        Ничего пока нет
    </p>
    {% endfor %}
</table>

{% endblock content %}

z09liner/forum/templates/forum/topic_filter_takepart.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<a href="{% url 'forum:category_list' %}" style="margin-left: 15%"> Вернуться на главную форума </a>
<h2 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px">Темы, в которых я принимаю участие</h2>
<h4 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px; color: #1b6d85">
   (найдено {{take_part_topics.count}} тем(ы)) </br>
</h4>


<table bgcolor="#add8e6" ; border="1"; bordercolor="#d3d3d3"; cellpadding="5"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="100%" style="text-align: center">
<!--        paginator-->
        </td>
    </tr>
</table>
<table bgcolor="#f0f8ff" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">

    {% for take_part_topic in take_part_topics %}
    <tr>
        <td width="60%">
            <a href="{% url 'forum:topic_detail' take_part_topic.pk %}" style="color: #18397c">{{take_part_topic}}</a>
            <hr style="margin: 0">
        </td>
        <td width="20%" style="font-size: 0.75em"> </td>
        <td width="20%" style="font-size: 0.75em"; align="right"> {{take_part_topic.posts.count}} </td>
    </tr>
    {% empty %}
    <p style="margin-left: 15%">
        По вашему запросу ничего не найдено
    </p>
    {% endfor %}
</table>

{% endblock content %}

z09liner/forum/templates/forum/topic_list.html
{% extends 'core/base.html' %}

{% load static %}
{% block content %}


<a href="{% url 'forum:category_list' %}" style="margin-left: 15%"> Вернуться на главную форума </a>
<!--<p style="margin-left: 15%"> Страница номер {{page.number}} </p>-->
<h2 style="margin-right: 15%; margin-left: 15%; margin-bottom: 20px">{{parent_topic.detail_title}}</h2>


<table bgcolor="#add8e6" ; border="1"; bordercolor="#d3d3d3"; cellpadding="5"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="20%"><p> Всего {{counter_topics}} тем(ы) </p></td>
        <td width="60%" style="text-align: center">
            <nav aria-label="..." style="margin-left: 15%">
                <ul class="pagination">
                  <li class="page-item">
                      {% if page.has_previous %}
                      <a class="page-link" href="{% url 'forum:topic_list' detail_pk=parent_topic.pk %}?page={{ page.previous_page_number }}" tabindex="-1">Предыдущая</a>
                      {% endif %}
                  </li>
                  {% for n in page.paginator.page_range %}
                  {% if page.number == n %}
                      <li class="page-item active">
                          <a class="page-link" href="{% url 'forum:topic_list' detail_pk=parent_topic.pk %}?page={{ n }}">{{n}}<span class="sr-only">(current)</span></a>
                      </li>
                  {% elif n > page.number|add:-3 and n < page.number|add:3 %}
                      <li class="page-item">
                          <a class="page-link" href="{% url 'forum:topic_list' detail_pk=parent_topic.pk %}?page={{ n }}">{{n}}</a>
                      </li>
                  {% endif %}
                  {% endfor %}
                  {% if page.has_next %}
                <li class="page-item">
                  <a class="page-link" href="{% url 'forum:topic_list' detail_pk=parent_topic.pk %}?page={{ page.next_page_number }}">Следующая</a>
                </li>
                  {% endif %}
                </ul>
            </nav>
        </td>
        <td width="20%"> <p style="text-align: right">Сообщений</p> </td>
    </tr>
</table>
<table bgcolor="#f0f8ff" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    {% for topic in page.object_list %}
    <tr>
        <td width="60%">
            <a href="{% url 'forum:topic_detail' topic.pk %}" style="color: #18397c">{{topic.title}}</a>
        </td>
        <td width="20%" style="font-size: 0.75em"> </br></td>
        <td width="20%" style="font-size: 0.75em"; align="right"> {{topic.posts.count}} </td>
    </tr>
{% empty %}
    <p style="margin-left: 15%">Здесь пока никто ничего не обсуждал - предложите свою тему для обсуждения</p>
{% endfor %}
</table>



<table bgcolor="#ffe4c4" ; cellpadding="5"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td style="text-align: left">
            <b style="color: red">Новая тема</b>
        </td>
    </tr>
</table>
<table bgcolor="#fffacd" ; border="1"; bordercolor="#f0f8ff"; cellpadding="10"; cellspacing="2"; width="70%" style="margin-left: 15%; margin-right: 15%">
    <tr>
        <td width="20%">
            {{post.author}}</br>
            {{post.author.image}}
        </td>
        <td width="80%">
            <form action="" method="POST"> {% csrf_token %}
            {{ topic_form.as_p }}
            <button type="submit" class="btn btn-warning">Отправить</button>
            </form>
        </td>
    </tr>
</table>

{% endblock content %}