z09liner/core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

z09liner/search/urls.py
from django.urls import path
from search.views import search

app_name = 'search'

urlpatterns = [
    path('', search, name='search'),
]

z09liner/service/urls.py
from django.urls import path, include


# Views
from service.views import service_home, category_list, service_detail, my_service, service_delete, \
    service_create, search

from service.contractor.views import contractor, contractor_detail, contractor_create, contractor_category, \
    my_contract, contractor_search, contractor_redact


app_name = 'service'


urlpatterns = [
    path('', service_home, name='service_home'),
    path('category_list/<int:cate_pk>/', category_list, name='category_list'),
    path('service_detail/<int:srv_pk>/', service_detail, name='service_detail'),
    path('my_service/', my_service, name='my_service'),
    path('contractor_create/', contractor_create, name='contractor_create'),
    path('contractor/', contractor, name='contractor'),
    path('contractor_detail/<int:cont_pk>', contractor_detail, name='contractor_detail'),
    path('contractor_category/<int:cate_pk>', contractor_category, name='contractor_category'),
    path('my_contract/', my_contract, name='my_contract'),
    path('contractor_redact/', contractor_redact, name='contractor_redact'),

    path('service_delete/<int:srv_pk>/', service_delete, name='service_delete'),
    path('service_create/', service_create, name='service_create'),
    path('search/', search, name='search'),
    path('contractor_search/', contractor_search, name='contractor_search'),
]

z09liner/system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

z09liner/users/urls.py
from django.urls import path
from users.views import login, register, profile, logout

app_name = 'users'


urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

z09liner/search/models.py
from django.db import models

# Create your models here.

z09liner/service/forms.py
from django import forms

# Models
from service.models import Category, Service, Comment, Contractor, Rating, CommentContract


class CommentForm(forms.ModelForm):
    class Meta:

        model = Comment

        fields = ['text']

        widgets = {'text': forms.Textarea(attrs={'rows': 1, 'cols': 50})}



class ServiceForm(forms.ModelForm):
    class Meta:

        model = Service

        fields = ['category', 'title', 'description', 'price', 'address', 'date_active', 'status', 'image']

        widgets = {'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   'category': forms.Select(attrs={'class': 'form-select', 'cols': 30}),
                   'status': forms.Select(attrs={'class': 'form-select'}),
                   'title': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
                   'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
                   'price': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
                   'date_active': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
                   }


class ContractorForm(forms.ModelForm):
    class Meta:

        model = Contractor

        fields = ['description', 'work', 'phone']

        widgets = {'work': forms.Select(attrs={'class': 'form-select'}),
                   'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   'phone': forms.Textarea(attrs={'class': 'form-control', 'rows': 1}),
                   }



class RatingForm(forms.ModelForm):


    class Meta:

        model = Rating

        fields = ['rating']

        widget = {'rating': forms.TextInput(attrs={'cols': 10})}


class CommentContractorForm(forms.ModelForm):
    class Meta:

        model = CommentContract

        fields = ['text']

        widgets = {'text': forms.Textarea(attrs={'rows': 1, 'cols': 50})}

z09liner/search/views.py
from django.db.models import Q
from django.shortcuts import render
from service.models import Service
from forum.models import Topic, Post


def search(request):
    zapros = request.GET.get('zapros')
    service_search = Service.objects.filter(
                                 Q(title__contains=zapros) |
                                 Q(description__contains=zapros)
                                 )
    forum_search = Topic.objects.filter(Q(title__contains=zapros))
    context = {
        'zapros': zapros, 'service_search': service_search,
        'forum_search': forum_search,
        }
    return render(request, 'search/search.html', context)

z09liner/service/contractor/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.http.response import HttpResponseRedirect

from service.models import Contractor, CommentContract, Category, Rating

from service.forms import ContractorForm, CommentContractorForm, RatingForm

from service.def_repeat import paginator
from service.contractor.contract_repeat import contract_category


def contractor(request):
    category = contract_category(request)
    contractor = Contractor.objects.all()
    comment_ct = CommentContract.objects.filter(user=request.user)

    page_obj = paginator(request, contractor)

    context = {
        'category': category,
        'page_obj': page_obj,
        'comment_ct': comment_ct
    }

    return render(request, 'service/contractor.html', context)


def contractor_category(request, cate_pk):
    category = contract_category(request)
    contractor = Contractor.objects.filter(work=cate_pk)

    page_obj = paginator(request, contractor)

    context = {'category': category, 'page_obj': page_obj}

    return render(request, 'service/contractor_category.html', context)


def contractor_detail(request, cont_pk):
    contractor = Contractor.objects.get(pk=cont_pk)
    comment_ct = CommentContract.objects.filter(contractor=cont_pk)

    if request.method == 'POST':

        comment_ct_form = CommentContractorForm(request.POST)
        if comment_ct_form.is_valid():
            ccf = comment_ct_form.save(commit=False)
            ccf.user = request.user
            ccf.contractor = contractor
            ccf.save()
            return redirect('service:contractor_detail', cont_pk)

        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            rf = rating_form.cleaned_data
            form_user = request.user
            Rating.objects.create(
                contractor=contractor,
                user=form_user,
                rating=rf['rating']
            )
            return redirect('service:contractor_detail', cont_pk=contractor.pk)

    else:
        rating_form = RatingForm()
        comment_ct_form = CommentContractorForm()


    context = {
        'contractor': contractor,
        'rating_form': rating_form,
        'comment_ct': comment_ct,
        'comment_ct_form': comment_ct_form
    }
    return render(request, 'service/contractor_detail.html', context)


@login_required
def contractor_create(request):
    contractor = Contractor.objects.all()

    if request.user.first_name == '':
        return redirect('users:profile')

    elif request.user.last_name == '':
        return redirect('users:profile')

    elif request.user.first_name != '' and request.user.last_name != '':
        return redirect('service:my_contract')

    else:
        if request.method == 'POST':
            contractor_form = ContractorForm(request.POST)
            if contractor_form.is_valid():
                cf = contractor_form.save(commit=False)
                cf.user = request.user
                cf.save()
                return redirect('service:contractor_create')
        else:
            contractor_form = ContractorForm()

    context = {
        'contractor_form': contractor_form
    }

    return render(request, 'service/contractor_create.html', context)


def my_contract(request):
    contractor = Contractor.objects.get(user=request.user)
    comment_ct = CommentContract.objects.filter(user=request.user)

    if request.method == 'POST':

        comment_ct_form = CommentContractorForm(request.POST)
        if comment_ct_form.is_valid():
            ccf = comment_ct_form.save(commit=False)
            ccf.user = request.user
            ccf.contractor = contractor
            ccf.save()
            return redirect('service:my_contract')


        rating_form = RatingForm(request.POST)
        if rating_form.is_valid():
            rf = rating_form.cleaned_data
            form_user = request.user
            Rating.objects.create(
                contractor=contractor,
                user=form_user,
                rating=rf['rating']
            )

            return redirect('service:my_contract')

    else:
        rating_form = RatingForm()
        comment_ct_form = CommentContractorForm()

    context = {'contractor': contractor,
               'comment_ct': comment_ct,
               'comment_ct_form': comment_ct_form,
               'rating_form': rating_form,}

    return render(request, 'service/my_contract.html', context)


def contractor_redact(request):
    contractor = get_object_or_404(Contractor, user=request.user)
    if request.method == 'GET':
        contractor_form = ContractorForm(instance=contractor)
        return render(request, 'service/contractor_redact.html', {'contractor_form': contractor_form})
    else:
        contractor_form = ContractorForm(request.POST, instance=contractor)
        if contractor_form.is_valid():
            cf = contractor_form.save(commit=False)
            cf.save()
            return redirect('service:my_contract')




def contractor_search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        contractor = Contractor.objects.filter(Q(user__username__contains=searched) |
                                               Q(user__first_name__contains=searched) |
                                               Q(user__last_name__contains=searched) |
                                               Q(description__contains=searched) |
                                               Q(work__name__contains=searched) |
                                               Q(phone__contains=searched))

        page_obj = paginator(request, contractor)

        context = {
            'searched': searched,
            'page_obj': page_obj
        }

        return render(request, 'service/contractor_search.html', context)

z09liner/service/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from currency.views import core_kurs_dollar
from weather.views import core_weather
# Models
from service.models import Service, Comment, Contractor, Category, Rating, CommentContract

# Forms
from service.forms import CommentForm, ServiceForm, ContractorForm, RatingForm, CommentContractorForm

# Repeat
from service.def_repeat import view_mixin, paginator


def service_home(request):
    page_obj = view_mixin(request, cate_pk=None, queryset=Service.objects.all())

    context = {
        'category': page_obj[0],
        'page_obj': page_obj[1][0],
        'my_filters': page_obj[1][1],
        'kurs_dollar': core_kurs_dollar(request),
        'core_weather': core_weather(request),
    }

    return render(request, 'service/base_service.html', context)


def category_list(request, cate_pk):
    page_obj = view_mixin(request, cate_pk=cate_pk, queryset=Service.objects.filter(category=cate_pk))
    count = Service.objects.filter(category=cate_pk)

    context = {
        'category': page_obj[0],
        'page_obj': page_obj[1][0],
        'my_filters': page_obj[1][1],
        'current_category': cate_pk,
        'count': count
    }

    return render(request, 'service/category_list.html', context)


def service_detail(request, srv_pk):
    service = Service.objects.get(pk=srv_pk)
    comment = Comment.objects.filter(service=srv_pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            cf = comment_form.save(commit=False)
            cf.user = request.user
            cf.service = service
            cf.save()
            return redirect('service:service_detail', srv_pk)
    else:
        comment_form = CommentForm()

    context = {
        'service': service,
        'comment': comment,
        'comment_form': comment_form
    }

    return render(request, 'service/service_detail.html', context)


@login_required
def my_service(request):
    page_obj = view_mixin(request, cate_pk=None, queryset=Service.objects.filter(user=request.user))

    context = {
        'page_obj': page_obj[1][0],
        'my_filters': page_obj[1][1]
    }

    return render(request, 'service/my_service.html', context)


@login_required
def service_delete(request, srv_pk):
    Service.objects.get(pk=srv_pk).delete()

    return redirect('service:my_service')


@login_required
def service_create(request):
    if request.method == 'POST':
        service_form = ServiceForm(request.POST)
        if service_form.is_valid():
            sf = service_form.save(commit=False)
            sf.user = request.user
            sf.save()
            return redirect('service:my_service')
    else:
        service_form = ServiceForm()

    context = {
        'service_form': service_form
    }

    return render(request, 'service/service_create.html', context)


def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        service = Service.objects.filter(Q(title__contains=searched) |
                                         Q(description__contains=searched) |
                                         Q(price__contains=searched))

        page_obj = paginator(request, service)

        context = {
            'searched': searched,
            'page_obj': page_obj,
        }

        return render(request, 'service/search.html', context)

z09liner/service/templates/service/contractor_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<!--Bootstrap-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



<!--Navibar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav me-auto mb-2 mb-lg-2" style="margin-left: 10px">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'service:service_home' %}">Заказы</a>
                    <a class="nav-link active" href="{% url 'service:contractor' %}">Исполнители</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:service_create' %}">Создать заказ</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:contractor_create' %}">Стать исполнителем</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:my_contract' %}">Моя страница</a>
                </li>
            </ul>
            <div>
                <form method="POST" class="d-flex" action="{% url 'service:contractor_search' %}" style="margin-left: 40px">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Искать в исполнителях" aria-label="Search"
                           name="searched">
                    <button type="submit" class="btn btn-outline-dark">Искать</button>
                </form>
            </div>
        </div>
    </div>
</nav>


<div style="text-align: center; border-bottom: solid; margin-top: 30px;">

    <h1 >{{ contractor.user.first_name }}  {{ contractor.user.last_name }}</h1><br>
    <h5>{{ contractor.work }}</h5>
    <h5> {{ contractor.description | linebreaks }}</h5>
    <h5>{{ service.phone }}</h5>
    Рейтинг : {{ contractor.get_average_review_score }} / 5.0
</div>


<div style="margin-left: 30px; margin-top: 30px;">
<form action="" method="POST">
    <a>Рейтинг: </a>
    {% csrf_token %}
    {{ rating_form.rating }}
    <input type="submit" value="Голосовать">
</form>
</div>

<!--Комментарии-->

<div style="margin: 30px">
    <h3>Отклики: </h3>
</div>

<div style="margin: 30px">

    {% if user.is_authenticated %}
    {% csrf_token %}
    <div class="comment-form">
        <div class='form-wrap'>
            <form action="" method="POST" style="display: flex; width: 100%">
                {{ comment_ct_form.text }}
                {% csrf_token %}
                <div style="padding-left: 10px;">
                    <button type="submit" class="btn btn-outline-dark" style="margin-top: -23px">Написать</button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <p>
        Чтобы оставить свое мнение, необходимо
        <a href="{% url 'users:login' %}">войти</a> или
        <a href="{% url 'users:register' %}">зарегистрироваться</a>
    </p>
    {% endif %}
    </br>
</div>

{% if comment_ct == None %}
<h1 style="text-align: center; margin-top: 30px">Нет откликов</h1>
{% else %}
<div style="">
    {% for ct in comment_ct %}
    <div style="margin-top: 30px; margin-right: 1100px; margin-left: 50px; border: solid; text-align: center">
        <small>{{ ct.user }}</small><br>
        <a>{{ ct.text }}</a><br>
        <small>{{ ct.date_create }}</small><br>
    </div>
    {% endfor %}
</div>
{% endif %}


<meta name="twitter:dnt" content="on" xmlns="http://www.w3.org/1999/html">
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


{% endblock content %}

z09liner/service/templates/service/my_contract.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<!--Bootstrap-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



<!--Navibar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav me-auto mb-2 mb-lg-2" style="margin-left: 10px">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'service:service_home' %}">Заказы</a>
                    <a class="nav-link active" href="{% url 'service:contractor' %}">Исполнители</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:service_create' %}">Создать заказ</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:contractor_create' %}">Стать исполнителем</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:my_contract' %}">Моя страница</a>
                </li>
            </ul>
            <div>
                <form method="POST" class="d-flex" action="{% url 'service:contractor_search' %}" style="margin-left: 40px">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Искать в исполнителях" aria-label="Search"
                           name="searched">
                    <button type="submit" class="btn btn-outline-dark">Искать</button>
                </form>
            </div>
        </div>
    </div>
</nav>

<div>
    <button><a href="{% url 'service:contractor_redact' %}">Редактировать</a></button>
</div>


<div style="text-align: center; border-bottom: solid; margin-top: 30px;">

    <h1 >{{ contractor.user.first_name }}  {{ contractor.user.last_name }}</h1><br>
    <h5>{{ contractor.work }}</h5>
    <h5> {{ contractor.description | linebreaks }}</h5>
    <h5>{{ service.phone }}</h5>
    Рейтинг : {{ contractor.get_average_review_score }} / 5.0
</div>



<!--Комментарии-->

<div style="margin: 30px">
    <h3>Отклики: {{ comment_ct.count }}</h3>
</div>

<div style="margin: 30px">

    {% if user.is_authenticated %}
    {% csrf_token %}
    <div class="comment-form">
        <div class='form-wrap'>
            <form action="" method="POST" style="display: flex; width: 100%">
                {{ comment_ct_form.text }}
                {% csrf_token %}
                <div style="padding-left: 10px;">
                    <button type="submit" class="btn btn-outline-dark" style="margin-top: -23px">Написать</button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <p>
        Чтобы оставить свое мнение, необходимо
        <a href="{% url 'users:login' %}">войти</a> или
        <a href="{% url 'users:register' %}">зарегистрироваться</a>
    </p>
    {% endif %}
    </br>
</div>

{% if comment_ct == None %}
<h1 style="text-align: center; margin-top: 30px">Нет откликов</h1>
{% else %}
<div style="">
    {% for ct in comment_ct %}
    <div style="margin-top: 30px; margin-right: 1100px; margin-left: 50px; border: solid; text-align: center">
        <small>{{ ct.user }}</small><br>
        <a>{{ ct.text }}</a><br>
        <small>{{ ct.date_create }}</small><br>
    </div>
    {% endfor %}
</div>
{% endif %}


<meta name="twitter:dnt" content="on" xmlns="http://www.w3.org/1999/html">
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


{% endblock content %}

z09liner/service/templates/service/service_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<!--Bootstrap-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>



<!--Navibar-->

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded" aria-label="Eleventh navbar example">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav me-auto mb-2 mb-lg-2" style="margin-left: 10px">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'service:service_home' %}">Заказы</a>
                    <a class="nav-link active" href="{% url 'service:contractor' %}">Исполнители</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:service_create' %}">Создать заказ</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:contractor_create' %}">Стать исполнителем</a>
                </li>
                <li class="nav-item" style="margin-left: 30px; margin-top: 20px">
                    <a class="nav-link active" href="{% url 'service:my_service' %}">Мои заказы</a>
                </li>

            </ul>
            <div>
                <form method="POST" class="d-flex" action="{% url 'service:search' %}" style="margin-left: 40px">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Искать в заказах" aria-label="Search"
                           name="searched">
                    <button type="submit" class="btn btn-outline-dark">Искать</button>
                </form>
            </div>
        </div>
    </div>
</nav>

<!--Sevice-->

<div style="text-align: center; border-bottom: solid; margin-top: 30px;">

    <h1 >{{ service.title }}</h1><br>
    <h5 style="margin-left: 50px; margin-right: 50px;">{{ service.description | linebreaks }}</h5><br>
    {% if service.image %}
        <div style="position: absolute; margin-top: -70px; margin-left: 30px;">
        </div>
    {% endif %}
    {% if service.price == None %}
        <h5>Цена : Договорная</h5>
    {% else %}
        <h5>Цена : {{ service.price }} руб</h5>
    {% endif %}
    <h5>Местоположение : {{ service.address }}</h5>
    <h5>Дата создания :</h5><h5>{{ service.user }} | {{ service.date_create }}</h5>
    <img src="{{ user.image.url }}">
    <h5>Активно до : {{ service.date_active }}</h5>
    <h5>Текущий статус : {{ service.status }}</h5>
</div>



<!--Комментарии-->

<div style="margin: 30px">
    <h3>Отклики: </h3>
</div>

<div style="margin: 30px">
    {% if user.is_authenticated %}
    {% csrf_token %}
    <div class="comment-form">
        <div class='form-wrap'>
            <form action="." method="post" style="display: flex; width: 100%">
                {{ comment_form.text }}
                {% csrf_token %}
                <div style="padding-left: 10px;">
                    <button type="submit" class="btn btn-outline-dark" style="margin-top: -23px">Написать</button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <p>
        Чтобы оставить свое мнение, необходимо
        <a href="{% url 'users:login' %}">войти</a> или
        <a href="{% url 'users:register' %}">зарегистрироваться</a>
    </p>
    {% endif %}
    </br>
</div>
{% if comment == None %}
    <h1 style="text-align: center; margin-top: 30px">Нет откликов</h1>
{% else %}
    <div style="">
    {% for cm in comment %}
    <div style="margin-top: 30px; margin-right: 1100px; margin-left: 50px; border: solid; text-align: center">
        <small>{{ cm.user }}</small><br>
        <a>{{ cm.text }}</a><br>
        <small>{{ cm.date_create }}</small><br>
    </div>
        {% empty %}
            <h4 style="text-align: center">В разделе "комментарии" пока что пусто</h4>
    {% endfor %}
    </div>
{% endif %}





<meta name="twitter:dnt" content="on" xmlns="http://www.w3.org/1999/html">
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


{% endblock content %}