z09liner/core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

z09liner/houses_and_apartments/urls.py
from django.urls import path
from .views import flat_list, flat_detail, placing_a_sale, rent_list, place_a_lease, rent_detail, expensive, \
    cheap, by_date,  my_announcements, my_announcements_rent, \
    expensive_rent, cheap_rent, by_date_rent, flat_edit, rent_edit, rent_delete, flat_delete, by_apartment, by_flat, \
    by_apartment_rent, by_flat_rent, sorting_by_room, sorting_by_room_rent


app_name = 'houses_and_apartments'


urlpatterns = [
    path('', flat_list, name='flat_list'),
    path('rent_list/', rent_list, name='rent_list'),
    path('detail/<int:detail_pk>/', flat_detail, name='flat_detail'),
    path('rent_detail/<int:detail_pk>/', rent_detail, name='rent_detail'),
    path('placing_a_sale/', placing_a_sale, name='placing_a_sale'),
    path('place_a_lease/', place_a_lease, name='place_a_lease'),
    path('expensive/', expensive, name='expensive'),
    path('expensive_rent/', expensive_rent, name='expensive_rent'),
    path('cheap/', cheap, name='cheap'),
    path('cheap_rent/', cheap_rent, name='cheap_rent'),
    path('my_announcements/', my_announcements, name='my_announcements'),
    path('my_announcements_rent/', my_announcements_rent, name='my_announcements_rent'),
    path('by_date/', by_date, name='by_date'),
    path('by_date_rent/', by_date_rent, name='by_date_rent'),
    path('flat_edit/<int:edit_pk>/', flat_edit, name='flat_edit'),
    path('rent_edit/<int:rent_edit_pk>/', rent_edit, name='rent_edit'),
    path('rent_delete/<int:rent_delete_pk>/', rent_delete, name='rent_delete'),
    path('flat_delete/<int:flat_delete_pk>/', flat_delete, name='flat_delete'),
    path('by_apartment/', by_apartment, name='by_apartment'),
    path('by_apartment_rent/', by_apartment_rent, name='by_apartment_rent'),
    path('by_flat/', by_flat, name='by_flat'),
    path('by_flat/sorting_by_room/', sorting_by_room, name='sorting_by_room'),

    path('by_flat_rent/', by_flat_rent, name='by_flat_rent'),
    path('by_flat_rent/sorting_by_room_rent/', sorting_by_room_rent, name='sorting_by_room_rent'),
]

z09liner/system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

z09liner/houses_and_apartments/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.models import User
from .filters import dollar


VARIANT = [
        ('Квартира', 'Квартира'),
        ('Дом', 'Дом')
    ]


class SaleFlat(models.Model):
    cost = models.PositiveIntegerField(verbose_name='стоимость квартиры')
    cost_dollar = models.FloatField(verbose_name='курс доллара', default=dollar)
    floor = models.PositiveIntegerField(verbose_name='этаж', default=1)
    total_area = models.DecimalField(verbose_name='общая площадь', max_digits=10, decimal_places=2)
    living_space = models.DecimalField(verbose_name='жилая площадь', max_digits=10, decimal_places=2)
    kitchen_area = models.DecimalField(verbose_name='площадь кухни', max_digits=10, decimal_places=2)
    ceiling_height = models.DecimalField(verbose_name='высота потолка', max_digits=10, decimal_places=2)
    number_of_rooms = models.PositiveIntegerField(verbose_name='количество комнат', default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='дата', auto_now_add=True)
    description = models.TextField(verbose_name='описание')
    telephone = models.CharField(verbose_name='номер телефона', max_length=25)
    address = models.CharField(verbose_name='адрес', max_length=50)
    flat_or_apartment = models.CharField(verbose_name='дом или квартира', choices=VARIANT, max_length=35)

    def __str__(self):
        return f'{self.address}'


class Photo(models.Model):
    image = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='картинка', blank=True, null=True)
    saleflat = models.ForeignKey('SaleFlat', on_delete=models.CASCADE, related_name='photo')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.last_name}, {self.id}'


class Rent(models.Model):
    cost = models.PositiveIntegerField(verbose_name='стоимость квартиры')
    cost_dollar = models.FloatField(verbose_name='курс доллара', default=dollar)
    floor = models.PositiveIntegerField(verbose_name='этаж', default=1)
    number_of_rooms = models.PositiveIntegerField(verbose_name='количество комнат', default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='дата', auto_now_add=True)
    description = models.TextField(verbose_name='описание')
    telephone = models.CharField(verbose_name='номер телефона', max_length=25)
    address = models.CharField(verbose_name='адрес', max_length=50)
    tv = models.BooleanField(verbose_name='телевизор', default=False)
    furniture = models.BooleanField(verbose_name='мебель', default=False)
    plate = models.BooleanField(verbose_name='плита', default=False)
    refrigerator = models.BooleanField(verbose_name='холодильник', default=False)
    internet = models.BooleanField(verbose_name='интернет', default=False)
    conditioning = models.BooleanField(verbose_name='кондиционер', default=False)
    washer = models.BooleanField(verbose_name='стиральная машина', default=False)
    flat_or_apartment = models.CharField(verbose_name='дом или квартира', choices=VARIANT, max_length=35)

    def __str__(self):
        return f'{self.address}'


class PhotoRent(models.Model):
    image_rent = models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='картинка', blank=True, null=True)
    rent = models.ForeignKey('Rent', on_delete=models.CASCADE, related_name='photo_rent')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.last_name}, {self.id}'

z09liner/houses_and_apartments/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, FormView
from .models import SaleFlat, Photo, Rent, PhotoRent
from .forms import FullFlatForm, FullRentForm
from django.core.paginator import Paginator
from .filters import dollar, foo_paginator, sessions, sort, filter_number_of_rooms


def flat_list(request):
    my_session = sessions(request)
    count = SaleFlat.objects.all().count()
    all_flat = foo_paginator(request, SaleFlat.objects.all(), 5)
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def flat_detail(request, detail_pk):
    flat = SaleFlat.objects.filter(pk=detail_pk).first()
    photo_flat = flat.photo.all()
    return render(request, 'houses_and_apartments/flat_detail.html', {'flat': flat, 'photo_flat': photo_flat})


def placing_a_sale(request):
    error = ''
    if request.method == 'POST':
        flatform = FullFlatForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('images')
        if flatform.is_valid():
            user = request.user
            cost = flatform.cleaned_data['cost']
            cost_dollar = int(cost/flatform.cleaned_data['cost_dollar'])
            floor = flatform.cleaned_data['floor']
            total_area = flatform.cleaned_data['total_area']
            living_space = flatform.cleaned_data['living_space']
            kitchen_area = flatform.cleaned_data['kitchen_area']
            ceiling_height = flatform.cleaned_data['ceiling_height']
            number_of_rooms = flatform.cleaned_data['number_of_rooms']
            description = flatform.cleaned_data['description']
            telephone = flatform.cleaned_data['telephone']
            address = flatform.cleaned_data['address']
            flat_or_apartment = flatform.cleaned_data['flat_or_apartment']
            flat_obj = SaleFlat.objects.create(user=user, cost=cost, floor=floor, total_area=total_area,
                                               living_space=living_space, kitchen_area=kitchen_area,
                                               ceiling_height=ceiling_height, number_of_rooms=number_of_rooms,
                                               description=description, telephone=telephone,
                                               address=address, cost_dollar=cost_dollar, flat_or_apartment=flat_or_apartment)
            for i in files:
                Photo.objects.create(user=user, saleflat=flat_obj, image=i)
            return redirect('houses_and_apartments:flat_detail', detail_pk=flat_obj.pk)

        else:
            error = 'Форма не валидна!!!'
    photoform = FullFlatForm()
    return render(request, 'houses_and_apartments/placing_a_sale.html', {'photoform': photoform, 'error': error})


def rent_list(request):
    my_session = sessions(request)
    count = Rent.objects.all().count()
    all_flat = foo_paginator(request, Rent.objects.all(), 5)
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def place_a_lease(request):
    error = ''
    if request.method == 'POST':
        fullrentform = FullRentForm(request.POST or None, request.FILES or None)
        files = request.FILES.getlist('photos')
        if fullrentform.is_valid():
            user = request.user
            cost = fullrentform.cleaned_data['cost']
            cost_dollar = int(cost / fullrentform.cleaned_data['cost_dollar'])
            floor = fullrentform.cleaned_data['floor']
            number_of_rooms = fullrentform.cleaned_data['number_of_rooms']
            description = fullrentform.cleaned_data['description']
            telephone = fullrentform.cleaned_data['telephone']
            address = fullrentform.cleaned_data['address']
            tv = fullrentform.cleaned_data['tv']
            furniture = fullrentform.cleaned_data['furniture']
            plate = fullrentform.cleaned_data['plate']
            refrigerator = fullrentform.cleaned_data['refrigerator']
            internet = fullrentform.cleaned_data['internet']
            conditioning = fullrentform.cleaned_data['conditioning']
            washer = fullrentform.cleaned_data['washer']
            flat_or_apartment = fullrentform.cleaned_data['flat_or_apartment']
            rent_obj = Rent.objects.create(user=user, cost=cost, floor=floor, number_of_rooms=number_of_rooms,
                                               description=description, telephone=telephone,
                                               address=address, tv=tv, furniture=furniture, plate=plate, refrigerator=refrigerator,
                                           internet=internet, conditioning=conditioning, washer=washer, cost_dollar=cost_dollar, flat_or_apartment=flat_or_apartment)
            for r in files:
                PhotoRent.objects.create(user=user, rent=rent_obj, image_rent=r)
            return redirect('houses_and_apartments:rent_detail', detail_pk=rent_obj.pk)

        else:
            error = 'Форма не валидна!!!'
    fullrentform = FullRentForm()
    return render(request, 'houses_and_apartments/place_a_lease.html', {'fullrentform': fullrentform, 'error': error})


def rent_detail(request, detail_pk):
    rent = Rent.objects.filter(pk=detail_pk).first()
    photo_rent = rent.photo_rent.all()
    return render(request, 'houses_and_apartments/rent_detail.html', {'rent': rent, 'photo_rent': photo_rent})


def expensive(request):
    sorts = sort(request, queryset=SaleFlat, order='-cost')
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def expensive_rent(request):
    sorts = sort(request, queryset=Rent, order='-cost')
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def cheap(request):
    sorts = sort(request, queryset=SaleFlat, order='cost')
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def cheap_rent(request):
    sorts = sort(request, queryset=Rent, order='cost')
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def by_date(request):
    sorts = sort(request, queryset=SaleFlat, order='-date')
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def by_date_rent(request):
    sorts = sort(request, queryset=Rent, order='-date')
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': sorts[0], 'count': sorts[1], 'dollar': dollar})


def by_apartment(request):
    my_session = sessions(request)
    count = SaleFlat.objects.filter(flat_or_apartment='Дом').count()
    all_flat = foo_paginator(request, SaleFlat.objects.filter(flat_or_apartment='Дом'), 5)
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def by_apartment_rent(request):
    my_session = sessions(request)
    count = Rent.objects.filter(flat_or_apartment='Дом').count()
    all_flat = foo_paginator(request, Rent.objects.filter(flat_or_apartment='Дом'), 5)
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def by_flat(request):
    my_session = sessions(request)
    count = SaleFlat.objects.filter(flat_or_apartment='Квартира').count()
    all_flat = foo_paginator(request, SaleFlat.objects.filter(flat_or_apartment='Квартира'), 5)
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def sorting_by_room(request):
    filter_rooms = filter_number_of_rooms(request, SaleFlat)
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': filter_rooms[1], 'count': filter_rooms[0], 'dollar': dollar})


def sorting_by_room_rent(request):
    filter_rooms = filter_number_of_rooms(request, Rent)
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': filter_rooms[1], 'count': filter_rooms[0], 'dollar': dollar})


def by_flat_rent(request):
    my_session = sessions(request)
    count = Rent.objects.filter(flat_or_apartment='Квартира').count()
    all_flat = foo_paginator(request, Rent.objects.filter(flat_or_apartment='Квартира'), 5)
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar, 'var': my_session})


def my_announcements(request):
    all_flat = SaleFlat.objects.filter(user=request.user)
    count = all_flat.count()
    all_flat = foo_paginator(request, all_flat, 5)
    return render(request, 'houses_and_apartments/flat_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar})


def my_announcements_rent(request):
    all_flat = Rent.objects.filter(user=request.user)
    count = all_flat.count()
    all_flat = foo_paginator(request, all_flat, 5)
    return render(request, 'houses_and_apartments/rent_list.html', {'all_flat': all_flat, 'count': count, 'dollar': dollar})


def flat_edit(request, edit_pk):
    error = ''
    flats = SaleFlat.objects.filter(pk=edit_pk).first()
    if request.method == 'GET':
        photoform = FullFlatForm(instance=flats)
        return render(request, 'houses_and_apartments/placing_a_sale.html', {'photoform': photoform, 'error': error})
    else:
        flatform = FullFlatForm(request.POST, request.FILES, instance=flats)
        files = request.FILES.getlist('images')
        if flatform.is_valid():
            flatform.save()
            user = request.user
            cost = flatform.cleaned_data['cost']
            cost_dollar = int(cost / flatform.cleaned_data['cost_dollar'])

z09liner/houses_and_apartments/templates/houses_and_apartments/flat_detail.html
{% extends 'core/base.html' %}

{% load static %}


{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
     <link href="/examples/vendors/bootstrap-4.3/css/bootstrap.min.css" rel="stylesheet">

<div align="center">
<button type="button" class="btn btn-warning"><a href="{% url 'houses_and_apartments:flat_list' %}"><h5>Продажа</h5></a></button>
<button type="button" class="btn btn-warning"><a href="{% url 'houses_and_apartments:rent_list' %}"><h5>Аренда</h5></a></button>
{% if flat.user == request.user %}
<button type="button" class="btn btn-warning"><h5><a href="{% url 'houses_and_apartments:flat_edit' edit_pk=flat.pk %}">Редактировать</a></h5></button>
<button type="button" class="btn btn-warning"><h5><a href="{% url 'houses_and_apartments:flat_delete' flat_delete_pk=flat.pk %}">Удалить объявление</a></h5></button>
{% endif %}
  <br>
  <br>
</div>
<div align="center" id="carouselExampleControls"  class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ photo_flat.first.image.url }}" class="d-block w-50"  width="200" height="600" alt="...">
    </div>
      {% for i in photo_flat %}
    <div class="carousel-item" >
      <img src="{{i.image.url}}" class="d-block w-50"  width="200" height="600" alt="...">
    </div>
    {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>
<br>

<p class="p-3 mb-2 bg-secondary text-white">Цена: {{flat.cost}} рублей</p>
<p class="p-3 mb-2 bg-warning text-dark">Цена: {{flat.cost_dollar}} $</p>
<p>Адрес: {{flat.address}}</p>
<p>Тип: {{flat.flat_or_apartment}}</p>
<p>Общая площадь: {{flat.total_area}}</p>
<p>Жилая площадь: {{flat.living_space}}</p>
<p>Площадь кухни: {{flat.kitchen_area}}</p>
<p>Количество комнат: {{flat.number_of_rooms}}</p>
<p>Высота потолка: {{flat.ceiling_height}}</p>
<p>телефон: {{flat.telephone}}</p>
<p>Продавец: {{flat.user.first_name}} {{flat.user.last_name}}</p>
<p>Описание: {{flat.description}}</p>
<p>Дата добавления:{{flat.date}}</p>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d75252.6725687754!2d27.523329546847982!3d53.88472079785735!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbcfd35b1e6ad3%3A0xb61b853ddb570d9!2z0JzQuNC90YHQug!5e0!3m2!1sru!2sby!4v1625153703989!5m2!1sru!2sby" width="2350" height="480" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
<script src="/examples/vendors/jquery/jquery-3.4.1.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="/examples/vendors/bootstrap-4.3/js/bootstrap.bundle.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
{% endblock content %}

z09liner/houses_and_apartments/templates/houses_and_apartments/flat_list.html
{% extends 'core/base.html' %}

{% load static %}


{% block content %}




 <h1  class="bg-secondary text-white" align="left"><a style=" margin-left: 10px;" class="bg-secondary text-white" align="left" href="{% url 'houses_and_apartments:flat_list' %}">z09liner<a/></h1>
<div class="row row-cols-3 row-cols-md-3 g-3">
    <div class="form-group text-right">
<button type="button" class="btn btn-warning "><a href="{% url 'houses_and_apartments:rent_list' %}?param=zero">Аренда</a></button>
<button type="button" class="btn btn-warning"><a href="{% url 'houses_and_apartments:flat_list' %}?param=zero">Продажа</a></button>
<button type="button" class="btn btn-warning"><a href="{% url 'houses_and_apartments:placing_a_sale' %}">Подать объявление</a></button>
        {% if user.is_authenticated %}
<button type="button" class="btn btn-warning"><a href="{% url 'houses_and_apartments:my_announcements' %}">Мои объявление</a></button>
        {% endif %}
</div>
</div>



<div class="btn-group" style="margin-top: -100px; margin-left: 5px;" >
  <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Выбрать
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item text-dark" href="{% url 'houses_and_apartments:expensive' %}">Сначала дорогие</a></li>
    <li><a class="dropdown-item text-dark" href="{% url 'houses_and_apartments:cheap' %}">Сначала дешевые</a></li>
    <li><a class="dropdown-item text-dark" href="{% url 'houses_and_apartments:by_date' %}">Сначала новые</a></li>
    <li><a class="dropdown-item text-dark" href="{% url 'houses_and_apartments:by_apartment' %}?param=Дом">Выбрать дома</a></li>
    <li><a class="dropdown-item text-dark" href="{% url 'houses_and_apartments:by_flat' %}?param=Квартира">Выбрать квартиры</a></li>
    <li><hr class="dropdown-divider"></li>
  </ul>
</div>
<br>
<br>
<br>


<div style="margin-top: -60px; margin-left: 5px;">
    <len class="p-3 mb-2 bg-secondary text-white" >Всего объявлений: {{count}}</len> <len class="p-3 mb-2 bg-warning text-dark">Курс доллара: {{dollar}}</len>
{% if var == 'Квартира' or var == 'Дом' %}
<a href="{% url 'houses_and_apartments:sorting_by_room' %}?param=1" class="p-3 mb-2 bg-secondary text-white">1-комнатные</a>
<a href="{% url 'houses_and_apartments:sorting_by_room' %}?param=2" class="p-3 mb-2 bg-secondary text-white">2-комнатные</a>
<a href="{% url 'houses_and_apartments:sorting_by_room' %}?param=3" class="p-3 mb-2 bg-secondary text-white">3-комнатные</a>
<a href="{% url 'houses_and_apartments:sorting_by_room' %}?param=4" class="p-3 mb-2 bg-secondary text-white">4+-комнатные</a>
{% endif %}
</div>
<br>




<div>
<div class="row row-cols-4 row-cols-md-5 g-4">
    {% for i in all_flat %}
<div class="card-group" >
  <div class="card">

     <a href="{% url 'houses_and_apartments:flat_detail' detail_pk=i.pk %}"><img src="{{i.photo.first.image.url}}" class="card-img-top" class="card-img-top" alt=".." width="200" height="300"></a>

    <div class="card-body">
      <p class="card-text"> Цена: {{i.cost}} рублей | Адрес: {{i.address}}</p>
        Цена: {{ i.cost_dollar }} $
    </div>
  </div>
</div>
    {% endfor %}
    </div>
    </div>



{% if all_flat.has_other_pages %}
<div class="text-center">
    {% if all_flat.has_previous %}
    <a href="?page={{ all_flat.previous_page_number }}">&lt;</a>
    {% endif %}


{% for p in all_flat.paginator.page_range %}
    {% if all_flat.number == p %}
    <em class="fs-2"><a href="?page={{ p }}"   class="text-secondary"> {{ p }} </a></em>
    {% elif p >= all_flat.number|add:-2 and p <= all_flat.number|add:2 %}
    <em class="fs-2"><a href="?page={{ p }}"   class=" text-dark" > {{ p }} </a></em>
    {% endif %}
{% endfor %}

    {% if all_flat.has_next %}
     <a href="?page={{ all_flat.next_page_number }}">&gt;</a>
    {% endif %}

</div>
{% endif %}
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d75252.6725687754!2d27.523329546847982!3d53.88472079785735!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbcfd35b1e6ad3%3A0xb61b853ddb570d9!2z0JzQuNC90YHQug!5e0!3m2!1sru!2sby!4v1625153703989!5m2!1sru!2sby" width="2350" height="480" style="border:0;" allowfullscreen="" loading="lazy"></iframe>


{% endblock content %}