z09liner/core/urls.py
from django.urls import path, include
from core.views import core_base

app_name = 'core'

urlpatterns = [
    path('', core_base, name='core_base'),
]

z09liner/shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from shop.views import index, product_detail, shopping_cart, basket_add, basket_delete, checkout, user_orders


app_name = 'shop'

urlpatterns = [
    path('', index, name='index'),
    path('<int:category_id>/', index, name='category'),
    path('page<int:page>/', index, name='page'),
    path('detail/<int:product_id>/', product_detail, name='product_detail'),
    path('shopping_cart/', shopping_cart, name='shopping_cart'),
    path('basket_add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket_delete/<int:product_id>/', basket_delete, name='basket_delete'),
    path('checkout/', checkout, name='checkout'),
    # path('confirm_order/', confirm_order, name='confirm_order'),
    path('order_history/', user_orders, name='user_orders'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

z09liner/system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('core.urls')),
    path('news/', include('news.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('users/', include('users.urls')),
    path('forum/', include('forum.urls')),
    path('weather/', include('weather.urls')),
    path('currency/', include('currency.urls')),
    path('shop/', include('shop.urls')),
    path('covid/', include('covid.urls')),
    path('search/', include('search.urls')),
    path('houses_and_apartments/', include('houses_and_apartments.urls')),
    path('service/', include('service.urls')),
    path('service/api/', include('service.api.urls')),
    path('used_cars/', include('used_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    path('shop/', include('shop.urls')),

z09liner/shop/models.py
from django.db import models
from users.models import User

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='media', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} || {self.category.name}'


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} || Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price


class Order(models.Model):
    products = models.ManyToManyField(Product, related_name='orders')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=12, decimal_places=2)
    created_date = models.DateTimeField(auto_now_add=True)
    email = models.CharField(max_length=50)
    tel = models.IntegerField(max_length=9)

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return f'{self.products}'

z09liner/shop/forms.py
from django import forms
from shop.models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'email',
            'tel',
        ]

z09liner/shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.paginator import Paginator

from shop.forms import OrderForm
from shop.models import ProductCategory, Product, Basket, Order

def paginator(request, name):

    paginator = Paginator(name, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request, category_id=None, page=1):
    categories = ProductCategory.objects.all()
    baskets = Basket.objects.filter(user=request.user)
    total_quantity = 0
    for _ in baskets:
        total_quantity += 1

    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    page_obj = paginator(request, products)

    context = {
        'categories': categories,
        'total_quantity': total_quantity,
        'baskets': baskets,
        'page_obj': page_obj
    }
    return render(request, 'shop/index.html', context)


def product_detail(request, product_id):
    categories = ProductCategory.objects.all()
    products = Product.objects.get(pk=product_id)
    baskets = Basket.objects.filter(user=request.user)
    total_quantity = 0
    for _ in baskets:
        total_quantity += 1
    context = {
        'product': products,
        'categories': categories,
        'baskets': baskets,
        'total_quantity': total_quantity,
    }
    return render(request, 'shop/product_detail.html', context)


def shopping_cart(request):
    categories = ProductCategory.objects.all()
    baskets = Basket.objects.filter(user=request.user)
    total_quantity = 0
    total_sum = 0
    for basket in baskets:
        total_quantity += 1
        total_sum += basket.sum()

    context = {
        'categories': categories,
        'baskets': baskets,
        'total_quantity': total_quantity,
        'total_sum': total_sum,
    }
    return render(request, 'shop/shopping_cart.html', context)


def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_delete(request, product_id):
    product = Basket.objects.get(id=product_id)
    product.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def checkout(request):
    categories = ProductCategory.objects.all()
    baskets = Basket.objects.filter(user=request.user)
    total_quantity = 0
    total_sum = 0
    for basket in baskets:
        total_quantity += 1
        total_sum += basket.sum()
    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            of = order_form.save(commit=False)

            order = Order.objects.create(
                user=request.user,
                total_price=total_sum,
                email=of.email,
                tel=of.tel,
                #как-то отправить продуты
            )
            order.save()

            return redirect('shop:user_orders')
    else:
        order_form = OrderForm()
    context = {
        'categories': categories,
        'baskets': baskets,
        'total_quantity': total_quantity,
        'total_sum': total_sum,
        'order_form': order_form,
    }
    return render(request, 'shop/checkout.html', context)


def user_orders(request):
    orders = Order.objects.filter(user=request.user)

    return render(request, 'shop/confirm_order.html', {'orders': orders})


# def confirm_order(request):
#     order = Order.objects.filter(user=request.user).first()
#     products = basket.product.all()
#     total_price = 0
#     for bas in basket:
#         total_price += bas.sum()
#     order = Order.objects.create(user=request.user, total_price=total_price)
#     order.products.add(*products)
#
#     basket.product.clear()
#     return redirect('user_orders')

z09liner/shop/templates/shop/checkout.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
<div id="content" class="float_r">
    <h2>Проверка</h2>
    <form method="POST">
        <div>
            {% csrf_token %}
            {{ order_form.as_p }}
            <button type="submit">Подтвердить заказ
            </button>
        </div>
    </form>
<!--    <div class="content_half float_r checkout">-->
<!--        Email:-->
<!--        <input type="text"  style="width:300px;"  /><br />-->
<!--        Телефон:<input type="text"  style="width:300px;"  />-->
<!--        <br />-->
<!--        <span style="font-size:10px">Пожалуйста, укажите Ваш доступный номер телефона. ВАМ ПОЗВОНЯТ, ЧТОБЫ ПРОВЕРИТЬ И ЗАВЕРШИТЬ ЗАКАЗ.</span>-->

<!--    </div>-->

    <div class="cleaner h50"></div>
    <h3>Ваш заказ:</h3>
    <table width="680px" cellspacing="0" cellpadding="5">
        <tr bgcolor="#ddd">
            <th width="220" align="left">Изображение </th>
            <th width="180" align="left">Описание </th>
            <th width="100" align="center">Количество </th>
            <th width="60" align="right">Цена </th>
            <th width="60" align="right">Итого </th>
            <th width="90"> </th>
        </tr>
        {% for product in baskets %}
        <tr>
            <td><a href="{% url 'shop:product_detail' product_id=product.product.pk%}"><img src="/media/{{ product.product.image }}" width="150" height="150" alt="{{ product.product.image }}" /></a></td>
            <td>{{ product.product }}</td>
            <td align="center"><input type="text" value="{{ product.quantity }}" style="width: 20px; text-align: right" /> </td>
            <td align="right">{{ product.product.price }}р.</td>
            <td align="right">{{ product.sum }}р.</td>
            <td align="center"> <a href="{% url 'shop:basket_delete' product_id=product.id %}">Удалить</a> </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3" align="right"  height="30px"></td>
            <td align="right" style="background:#ddd; font-weight:bold"> Итого </td>
            <td align="right" style="background:#ddd; font-weight:bold">{{ total_sum }}р.</td>
            <td style="background:#ddd; font-weight:bold"> </td>
        </tr>
        </table>



</div>
<div class="cleaner"></div>



{% endblock content %}

z09liner/shop/templates/shop/confirm_order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заказы</title>
</head>
<body>
<p><a href="{% url 'shop:index' %}"> На главную страницу </a></p>
<h1> Ваш заказ принят </h1>


<h2> История заказов </h2>


{% for order in orders %}
    {% for product in order.products.all %}
        {{product.orders}}<br>
    {% endfor %}

    {{order.orders.product}}
    {{order.total_price}}p.<br>
    {{order.created_date}}<br>
    {{order.email}}<br>
    {{order.tel}}<br>

<br>
{% endfor %}


</body>
</html>

z09liner/shop/templates/shop/index.html
{% extends 'core/base.html' %}
{% load static %}




{% block content %}
<div class="floatleft">
  <h3>Категории</h3>
    <ul>
      {% for category in categories %}
        <li><a href="{% url 'shop:category' category_id=category.pk %}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
  <br>
  <div> <a href="{% url 'shop:index' %}">На главную </a></div>
</div>

<div class="floatright">
    <div id="top_shopping_cart">
      Ваша козина: <strong> {{ total_quantity }} товаров </strong> ( <a href="{% url 'shop:shopping_cart' %}">Показать корзину</a> )
    </div>

  {% for product in page_obj %}
  <div class="product_box">

    <a href="{% url 'shop:product_detail' product_id=product.pk%}"><img src="/media/{{ product.image }}" width="150" height="150" alt="{{ product.image }}" /></a>
    <h3>{{ product.name }}</h3>
    <p class="product_price">{{ product.price }}р.</p>
    <a href="{% url 'shop:basket_add' product_id=product.pk%}" class="add_to_card">Добавить в корзину</a>
    <a href="{% url 'shop:product_detail' product_id=product.pk%}" class="detail">Подробнее</a>

  </div>
  {% endfor %}

<div class="pagination" style="margin-left: 250px; margin-top: 30px;">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
            {% endif %}

            <span class="current">
                Страница: {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Дальше</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>

<!--<ul class="pagination justify-content-center">-->
<!--    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">-->
<!--        <a class="page-link"-->
<!--           href="{% if page_obj.has_previous %} {% url 'shop:page' page_obj.previous_page_number %} {% else %} # {% endif %}"-->
<!--           tabindex="-1" aria-disabled="true">Предыдущая</a>-->
<!--    </li>-->
<!--    {% for page in page_obj.page_range %}-->
<!--        <li class="page-item">-->
<!--            <a class="page-link" href="{% url 'shop:page' page %}">-->
<!--                {{ page }}-->
<!--            </a>-->
<!--        </li>-->

<!--    {% endfor %}-->

<!--    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">-->
<!--        <a class="page-link"-->
<!--           href="{% if page_obj.has_next %} {% url 'shop:page' page_obj.next_page_number %} {% else %} # {% endif %}">-->
<!--            Следующая</a>-->
<!--    </li>-->
<!--</ul>-->

</div>

{% endblock content %}

z09liner/shop/templates/shop/product_detail.html
{% extends 'core/base.html' %}
{% load static %}




{% block content %}
<div class="floatleft">
  <h3>Категории</h3>
    <ul>
      {% for category in categories %}
        <li><a href="{% url 'shop:category' category_id=category.pk %}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
  <br>
  <div> <a href="{% url 'shop:index' %}">На главную </a></div>
</div>


<div class="floatright">
  <div id="top_shopping_cart">
      Ваша козина: <strong> {{ total_quantity }} товаров </strong> ( <a href="{% url 'shop:shopping_cart' %}">Показать корзину</a> )
  </div>
  <img src="/media/{{ product.image }}" width="150" height="150" alt="{{ product.image }}" />
  <h3>{{ product.name }}</h3>
  <p>{{ product.description }}</p>
  <p>{{ product.price }}р.</p>
  <a href="{% url 'shop:basket_add' product_id=product.pk%}" class="add_to_card">Добавить в корзину</a>

</div>

{% endblock content %}

z09liner/shop/templates/shop/shopping_cart.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
<div class="floatleft">
  <h3>Категории</h3>
    <ul>
      {% for category in categories %}
        <li><a href="{% url 'shop:category' category_id=category.pk %}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
  <br>
  <div> <a href="{% url 'shop:index' %}">На главную </a></div>
</div>

<div class="floatright">

<!--	<div id="templatemo_header">-->
<!--        <div id="header_right">-->
<!--	        <a href="#">My Account</a> | <a href="#">My Wishlist</a> | <a href="#">My Cart</a> | <a href="#">Checkout</a> | <a href="#">Log In</a>-->
<!--		</div>-->
<!--        <div class="cleaner"></div>-->
<!--    </div> &lt;!&ndash; END of templatemo_header &ndash;&gt;-->
    {% if baskets %}
        <h1>Ваша корзина ({{ total_quantity }} товаров)</h1>
        <table width="680px" cellspacing="0" cellpadding="5">
        <tr bgcolor="#ddd">
            <th width="220" align="left">Изображение </th>
            <th width="180" align="left">Описание </th>
            <th width="100" align="center">Количество </th>
            <th width="60" align="right">Цена </th>
            <th width="60" align="right">Итого </th>
            <th width="90"> </th>
        </tr>
        {% for product in baskets %}
        <tr>
            <td><a href="{% url 'shop:product_detail' product_id=product.product.pk%}"><img src="/media/{{ product.product.image }}" width="150" height="150" alt="{{ product.product.image }}" /></a></td>
            <td>{{ product.product }}</td>
            <td align="center"><input type="text" value="{{ product.quantity }}" style="width: 20px; text-align: right" /> </td>
            <td align="right">{{ product.product.price }}р.</td>
            <td align="right">{{ product.sum }}р.</td>
            <td align="center"> <a href="{% url 'shop:basket_delete' product_id=product.id %}">Удалить</a> </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="3" align="right"  height="30px"></td>
            <td align="right" style="background:#ddd; font-weight:bold"> Итого </td>
            <td align="right" style="background:#ddd; font-weight:bold">{{ total_sum }}р.</td>
            <td style="background:#ddd; font-weight:bold"> </td>
        </tr>
        </table>
        <div style="float:left; width: 300px; margin-top: 20px;">

        <p><a href="{% url 'shop:checkout' %}">Перейти к оформлению заказа</a></p>
        <p><a href="{% url 'shop:index' %}">Продолжить покупки</a></p>

        </div>
            <div class="cleaner"></div>
    {% else %}
        <h1>Ваша корзина пуста</h1>
        <p><a href="{% url 'shop:index' %}">Перейти к покупкам</a></p>
        <div class="cleaner"></div>
    {% endif %}

{% endblock content %}